/*
 * GPIO_config.c
 *
 *  Created on: Aug 23, 2022
 *      Author: Hosam
 */

#include "LIB/STD_TYPES.h"

#include "MCAL/GPIO_interface.h"
#include "MCAL/GPIO_config.h"
#include "MCAL/GPIO_private.h"

/*
 * I2C :
 *
 * ALT_FUNC
 * OPEN_DRAIN
 * VERY_HIGH
 * PULL_UP
 */

/*
 * UART :
 *
 * ALT_FUNC
 * PUSH_PULL
 * VERY_HIGH
 * NO_PULL_UP_DOWN
 */

/*
 * PWM :
 *
 * ALT_FUNC
 * PUSH_PULL
 * NORMAL
 * NO_PULL_UP_DOWN
 */

/*
 * INPUT CAPTURE :
 *
 * ALT_FUNC
 * PUSH_PULL
 * NORMAL
 * NO_PULL_UP_DOWN
 */

PIN_CONFIG	GLOB_prtStrPins[NUMBER_OF_USED_PINS] =
{									/*ADC*/
		[0] = {PORT_A, PIN0, ANALOG, GPIO_NOT_USED, GPIO_NOT_USED, GPIO_NOT_USED, GPIO_NOT_USED},
		[1] = {PORT_A, PIN1, ANALOG, GPIO_NOT_USED, GPIO_NOT_USED, GPIO_NOT_USED, GPIO_NOT_USED},

									/*PWM*/
		[2] = {PORT_A, PIN2, ALT_FUNC, PUSH_PULL, NORMAL, NO_PULL_UP_DOWN, AF_1},
		[3] = {PORT_A, PIN3, ALT_FUNC, PUSH_PULL, NORMAL, NO_PULL_UP_DOWN, AF_1},

									/*OUTPUT*/
		[4] = {PORT_A, PIN4, OUTPUT, PUSH_PULL, NORMAL, GPIO_NOT_USED, GPIO_NOT_USED},
		[5] = {PORT_A, PIN5, OUTPUT, PUSH_PULL, NORMAL, GPIO_NOT_USED, GPIO_NOT_USED},

									/*INPUT CAPTURE*/
		[6] = {PORT_A, PIN6, ALT_FUNC, PUSH_PULL, NORMAL, NO_PULL_UP_DOWN, AF_2},
		[7] = {PORT_A, PIN7, ALT_FUNC, PUSH_PULL, NORMAL, NO_PULL_UP_DOWN, AF_2},

									/*I2C*/
		[8] = {PORT_B, PIN7, ALT_FUNC, OPEN_DRAIN, VERY_HIGH, PULL_UP, AF_4},
		[9] = {PORT_B, PIN8, ALT_FUNC, OPEN_DRAIN, VERY_HIGH, PULL_UP, AF_4},

		[10] = {PORT_B, PIN3, ALT_FUNC, OPEN_DRAIN, VERY_HIGH, PULL_UP, AF_9},
		[11] = {PORT_B, PIN10, ALT_FUNC, OPEN_DRAIN, VERY_HIGH, PULL_UP, AF_4},
};
