/*
 * ADC_config.h
 *
 *  Created on: Oct 23, 2022
 *      Author: Hosam
 */

#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

#include "MCAL/ADC_interface.h"


/*
 * Select ADC Alignment from :
 * 	RIGHT_ALIGNMENT
 * 	LEFT_ALIGNMENT
 */			
#define CHANNEL0_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL1_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL2_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL3_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL4_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL5_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL6_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL7_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL8_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL9_ADC_ALIGN      RIGHT_ALIGNMENT
#define CHANNEL10_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL11_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL12_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL13_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL14_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL15_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL16_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL17_ADC_ALIGN     RIGHT_ALIGNMENT
#define CHANNEL18_ADC_ALIGN     RIGHT_ALIGNMENT

/*
 * Select ADC Resolution from :
 * 	_12_BITS_ADC
 *  _10_BITS_ADC
 *  _8_BITS_ADC,
 *  _6_BITS_ADC,
 */
#define CHANNEL0_ADC_RESOL      _12_BITS_ADC
#define CHANNEL1_ADC_RESOL      _12_BITS_ADC
#define CHANNEL2_ADC_RESOL      _12_BITS_ADC
#define CHANNEL3_ADC_RESOL      _12_BITS_ADC
#define CHANNEL4_ADC_RESOL      _12_BITS_ADC
#define CHANNEL5_ADC_RESOL      _12_BITS_ADC
#define CHANNEL6_ADC_RESOL      _12_BITS_ADC
#define CHANNEL7_ADC_RESOL      _12_BITS_ADC
#define CHANNEL8_ADC_RESOL      _12_BITS_ADC
#define CHANNEL9_ADC_RESOL      _12_BITS_ADC
#define CHANNEL10_ADC_RESOL     _12_BITS_ADC
#define CHANNEL11_ADC_RESOL     _12_BITS_ADC
#define CHANNEL12_ADC_RESOL     _12_BITS_ADC
#define CHANNEL13_ADC_RESOL     _12_BITS_ADC
#define CHANNEL14_ADC_RESOL     _12_BITS_ADC
#define CHANNEL15_ADC_RESOL     _12_BITS_ADC
#define CHANNEL16_ADC_RESOL     _12_BITS_ADC
#define CHANNEL17_ADC_RESOL     _12_BITS_ADC
#define CHANNEL18_ADC_RESOL     _12_BITS_ADC

#endif
