/*********************************
Author	:	Hosam Magdy
Date	:	22 July 2022
Version	:	1.0
*********************************/
#ifndef	RCC_CONFIG_H
#define	RCC_CONFIG_H

#include "MCAL/RCC_interface.h"

/*
 * OPTIONS FOR SELECTING SYSCLOCK SOURCE:
 * HSI
 * HSE_CRYSTAL
 * HSE_CRYSTAL_WITH_CLK_SECURITY
 * HSE_RC
 * HSE_RC_WITH_CLK_SECURITY
 * PLL
 */
#define RCC_SYSCLOCK				HSI

/*
 * OPTIONS FOR SELECTING PLL SOURCE:
 * PLL_HSI
 * PLL_HSE
 */
#define RCC_PLL_SOURCE				PLL_HSI

/*
 * OPTIONS FOR SELECTING SYSCLK PRESCALER FOR AHB:
 * SYSCLK_NO_PRESCALER
 * SYSCLK_DIVIDED_BY_2
 * SYSCLK_DIVIDED_BY_4
 * SYSCLK_DIVIDED_BY_8
 * SYSCLK_DIVIDED_BY_16
 * SYSCLK_DIVIDED_BY_64
 * SYSCLK_DIVIDED_BY_128
 * SYSCLK_DIVIDED_BY_256
 * SYSCLK_DIVIDED_BY_512
 */
#define RCC_SYSCLK_PRESCALER_AHB	SYSCLK_NO_PRESCALER

/*
 * OPTIONS FOR SELECTING AHB PRESCALER FOR APB1
 * AHB1_NO_PRESCALER
 * AHB1_DIVIDED_BY_2
 * AHB1_DIVIDED_BY_4
 * AHB1_DIVIDED_BY_8
 * AHB1_DIVIDED_BY_16
 */
#define RCC_AHB_PRESCALER_APB1		AHB1_NO_PRESCALER

/*
 * OPTIONS FOR SELECTING AHB PRESCALER FOR APB2
 * AHB1_NO_PRESCALER
 * AHB1_DIVIDED_BY_2
 * AHB1_DIVIDED_BY_4
 * AHB1_DIVIDED_BY_8
 * AHB1_DIVIDED_BY_16
 */
#define RCC_AHB_PRESCALER_APB2		AHB1_NO_PRESCALER

#endif
