manipulator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # posiiton controller
  left_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: back_left_joint
    pid: {p: 100.0, i: 0.0, d: 1.0}

  right_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: back_right_joint
    pid: {p: 100.0, i: 0.0, d: 1.0}



